[phases.setup]
commands = [
    "gradle wrapper"
]

[phases.build]
commands = [
    "./gradlew build",
    "ls -l build/libs"
]

[phases.start]
commands = [
    "java -jar build/libs/api-bootcamp-santander-0.0.1-SNAPSHOT.jar"
]

[build]
builder = "gradle"
