#project = "api-bootcamp-santander"
#
#[services.web]
#port = 8080
#command = "java -jar target/api-bootcamp-santander-0.0.1-SNAPSHOT.jar"

[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10